version: '3.8'

services:
  # Database Service
  db:
    image: postgres:15-alpine
    container_name: notes-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend Service
  backend:
    build: ./backend
    container_name: notes-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/notes_db
      - PORT=3001
      - NODE_ENV=production
    depends_on:
      - db

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=http://9.223.179.72:3001
    container_name: notes-frontend
    # ... digər hissələr eyni qalır
    container_name: notes-frontend
    restart: always
    ports:
      - "3000:80"
    environment:
      # VM IP
      - REACT_APP_API_URL=http://9.223.179.72:3001
    depends_on:
      - backend

volumes:
  postgres_data:
